### PR TITLE
Add new dependencies for HomologyAnnotation pipeline

### PR DESCRIPTION
**Pull request by JAlvarezJarreta**
`OrthoFinder` is a new software that we are aiming to include into our homology prediction system for the rapid release. It requires `diamond`, `mcl` and `FastME`. The first stage is to add it to the `HomologyAnnotation` pipeline, thus the changes in both casks.

Depends on https://github.com/Ensembl/homebrew-external/pull/14 and https://github.com/Ensembl/homebrew-ensembl/pull/44 / https://github.com/Ensembl/homebrew-ensembl/pull/45.

### CODE REVIEW

**Comment by thiagogenez** [comment]
Looks good to me, @JAlvarezJarreta

**Comment by JAlvarezJarreta** [comment]
Cask updated following the suggestions in https://github.com/Ensembl/homebrew-external/pull/14.

**Comment by thiagogenez** [comment]
Looks good again.

**Review by thibauthourlier — APPROVED** [review]
Sounds good to me

**Pull request merged**
