### PR TITLE
Switching to ensembl/external and homebrew-core

### PR DESCRIPTION
**Pull request by andrewyatz**
A number of formulas have moved either to ensembl/external or into the core homebrew taps as homebrew-science is no longer available. This should be all of them

### CODE REVIEW

**Comment by andrewyatz** [comment]
This is the complementary PR to Ensembl/homebrew-ensembl#16

**Review by carlacummins — COMMENTED** [review]
There's a leftover reference to homebrew/science in compara-epo.rb

**Review by carlacummins — COMMENTED** [review]
genometools, bowtie2 and bwa are missing ensembl/external reference in eg-alignment.rb

**Comment by andrewyatz** [comment]
@carlacummins genometools, bowtie2 and bwa all made it into `Linuxbrew/homebrew-core` and not into `ensembl/external` so those do not need the extension. Fixed the epo issue.

**Review by muffato — APPROVED** [review]

**Comment by andrewyatz** [comment]
Merging

**Pull request merged**
